module.exports = {
    FB_PAGE_TOKEN: 'YOUR FACEBOOK PAGE TOKEN',
    FB_VERIFY_TOKEN: 'YOUR TOKEN',
    API_AI_CLIENT_ACCESS_TOKEN: 'YOUR API.AI CLIENT ACCESS TOKEN',
    FB_APP_SECRET: 'YOUR FACEBOOK APP SECRET',
    SERVER_URL: "PUT YOUR SERVER URL",
    SENDGRID_API_KEY: 'Your key'
    EMAIL_TO:'PUT A EMAIL'
    EMAIL_FROM:'PUT A EMAIL'
    WEATHER_API_KEY: 'YOUR WEATHER API KEY'(THIS IS JUST AN EXTENTION FOR KNOWING WEATHER FROM YOUR CHATBOT)
};
